services:
  memgpt_server:
    image: memgpt/memgpt-server:latest
    hostname: memgpt-server
    ports:
      - "8283:8283"
    env_file:
      - .env
    environment:
      - POSTGRES_URI=postgresql://${MEMGPT_PG_USER}:${MEMGPT_PG_PASSWORD}@${MEMGPT_PG_HOST}/${MEMGPT_PG_DB}
      - MEMGPT_SERVER_PASS=${MEMGPT_SERVER_PASS} # memgpt server password
      - MEMGPT_PG_DB=${MEMGPT_PG_DB}
      - MEMGPT_PG_USER=${MEMGPT_PG_USER}
      - MEMGPT_PG_PASSWORD=${MEMGPT_PG_PASSWORD}
      - MEMGPT_PG_HOST=pgvector_db
      - MEMGPT_PG_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./configs/server_config.yaml:/root/.memgpt/config # config file
      - ~/.memgpt/credentials:/root/.memgpt/credentials # credentials file
